version: '3.8'

services:
  grafana:
    image: grafana/grafana

  jaeger:
    image: jaegertracing/all-in-one

  prometheus:
    image: prom/prometheus

  loki:
    image: grafana/loki

  promtail:
    image: grafana/promtail

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest

  rabbitmq:
    image: rabbitmq:management-alpine

  pudicitia-identity-api:
    image: ${DOCKER_REGISTRY-}pudicitia-identity-api
    build:
      context: .
      dockerfile: src/Pudicitia.Identity.Api/Dockerfile
    depends_on:
      - jaeger
      - mssql
      - rabbitmq

  pudicitia-hr-api:
    image: ${DOCKER_REGISTRY-}pudicitia-hr-api
    build:
      context: .
      dockerfile: src/Pudicitia.HR.Api/Dockerfile
    depends_on:
      - jaeger
      - mssql
      - rabbitmq

  pudicitia-enterprise-gateway:
    image: ${DOCKER_REGISTRY-}pudicitia-enterprise-gateway
    build:
      context: .
      dockerfile: src/Pudicitia.Enterprise.Gateway/Dockerfile
    depends_on:
      - jaeger
      - pudicitia-identity-api
      - pudicitia-hr-api
