version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest

  pudicitia-identity-api:
    image: ${DOCKER_REGISTRY-}pudicitia-identity-api
    build:
      context: .
      dockerfile: src/Pudicitia.Identity.Api/Dockerfile

  pudicitia-hr-api:
    image: ${DOCKER_REGISTRY-}pudicitia-hr-api
    build:
      context: .
      dockerfile: src/Pudicitia.HR.Api/Dockerfile
    depends_on:
      - mssql

  pudicitia-enterprise-gateway:
    image: ${DOCKER_REGISTRY-}pudicitia-enterprise-gateway
    build:
      context: .
      dockerfile: src/Pudicitia.Enterprise.Gateway/Dockerfile
    depends_on:
      - pudicitia-identity-api
      - pudicitia-hr-api
