version: '3.8'

services:
  grafana:
    ports:
      - "3000:3000"
    volumes:
      - pudicitia-grafana:/var/lib/grafana

  prometheus:
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - pudicitia-prometheus:/etc/prometheus

  jaeger:
    ports:
      - "5778"
      - "6831/udp"
      - "16686"

  mssql:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@word
    ports:
      - "1433:1433"
    volumes:
      - pudicitia-mssql:/var/opt/mssql

  rabbitmq:
    ports:
      - "5672"
      - "15672:15672"
    volumes:
      - pudicitia-rabbitmq:/var/lib/rabbitmq

  pudicitia-identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__Database=Server=mssql;Database=Pudicitia.Identity;User Id=sa;Password=Pass@word;MultipleActiveResultSets=True;
      - ConnectionStrings__RabbitMQ=host=rabbitmq
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLING_ENDPOINT=http://jaeger:5778/sampling
      - JAEGER_SERVICE_NAME=Pudicitia.Identity
    ports:
      - "80"
      - "7000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  pudicitia-hr-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__Database=Server=mssql;Database=Pudicitia.HR;User Id=sa;Password=Pass@word;MultipleActiveResultSets=True;
      - ConnectionStrings__RabbitMQ=host=rabbitmq
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLING_ENDPOINT=http://jaeger:5778/sampling
      - JAEGER_SERVICE_NAME=Pudicitia.HR
    ports:
      - "80"
      - "7200:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  pudicitia-enterprise-gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Apis__Identity=https://pudicitia-identity-api
      - Apis__HR=https://pudicitia-hr-api
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLING_ENDPOINT=http://jaeger:5778/sampling
      - JAEGER_SERVICE_NAME=Pudicitia.Enterprise
    ports:
      - "80"
      - "7100:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
  pudicitia-grafana: {}

  pudicitia-prometheus: {}

  pudicitia-mssql: {}

  pudicitia-rabbitmq: {}
