version: '3.8'

services:
  grafana:
    ports:
      - "3000:3000"
    volumes:
      - pudicitia-grafana:/var/lib/grafana

  jaeger:
    ports:
      - "5778"
      - "6831/udp"
      - "16686"

  prometheus:
    ports:
      - "9090:9090"
    volumes:
      - pudicitia-prometheus:/etc/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  loki:
    ports:
      - "3100"

  promtail:
    volumes:
      - pudicitia-promtail:/var/log

  mssql:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@word
    ports:
      - "1433:1433"
    volumes:
      - pudicitia-mssql:/var/opt/mssql

  rabbitmq:
    ports:
      - "5672"
      - "15672:15672"
    volumes:
      - pudicitia-rabbitmq:/var/lib/rabbitmq

  pudicitia-identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__Database=Server=mssql;Database=PudicitiaIdentity;User Id=sa;Password=Pass@word;MultipleActiveResultSets=True;Encrypt=False;
      - ConnectionStrings__EventBus=amqp://rabbitmq
      - Jaeger__ServiceName=Pudicitia.Identity
      - Jaeger__AgentHost=jaeger
      - Jaeger__AgentPort=6831
      - Serilog__Loki=http://loki:3100
    ports:
      - "80"
      - "7000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  pudicitia-hr-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__Database=Server=mssql;Database=PudicitiaHR;User Id=sa;Password=Pass@word;MultipleActiveResultSets=True;Encrypt=False;
      - ConnectionStrings__EventBus=amqp://rabbitmq
      - Jaeger__ServiceName=Pudicitia.HR
      - Jaeger__AgentHost=jaeger
      - Jaeger__AgentPort=6831
      - Serilog__Loki=http://loki:3100
    ports:
      - "80"
      - "7200:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  pudicitia-enterprise-gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Apis__Identity=https://pudicitia-identity-api
      - Apis__HR=https://pudicitia-hr-api
      - Jaeger__ServiceName=Pudicitia.Enterprise
      - Jaeger__AgentHost=jaeger
      - Jaeger__AgentPort=6831
      - Serilog__Loki=http://loki:3100
      - Jwt__Authority=https://host.docker.internal:7000
      - Jwt__ValidIssuer=https://localhost:7000
    ports:
      - "80"
      - "7100:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
  pudicitia-grafana: {}

  pudicitia-prometheus: {}

  pudicitia-promtail: {}

  pudicitia-mssql: {}

  pudicitia-rabbitmq: {}
